# Generated by Django 2.1.7 on 2019-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objective', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Done'), (3, 'Warning')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='complete_date',
            field=models.DateField(),
        ),
    ]
