# Generated by Django 2.1.7 on 2019-04-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objective', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='leader_assessment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objective',
            name='self_assessment_score',
            field=models.IntegerField(default=0),
        ),
    ]
